---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 2m

  chart:
    spec:
      chart: cert-manager
      version: v1.0.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: gotk-system
      interval: 5m

  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: false
        labels:
          release: monitoring
