resources:
  - gotk/
  - istio/
  - observability/
  - cert-manager/
  - gatekeeper/
#  - rancher/

patches:
    # Add common parameters to all HelmReleases
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
    patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: common
      spec:
        test:
          enable: false
        install:
          remediation:
            retries: 5
        upgrade:
          remediation:
            retries: 3
            remediateLastFailure: true
          cleanupOnFail: true
        rollback:
          timeout: 1m
          cleanupOnFail: true

configMapGenerator:
  - name: global-configs
    namespace: gotk-system
    envs:
      - globals.env

vars:
  - name: hostname
    objref:
      kind: ConfigMap
      name: global-configs
      apiVersion: v1
    fieldref:
      fieldpath: data.hostname

configurations:
  - kconfig.yaml