---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 2m
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gotk-system
      interval: 5m

  test:
    enable: false

  install:
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 1m
    cleanupOnFail: true

  values:
    global:
      ingress:
        enabled: false
        configureCertmanager: false
      hosts:
        domain: gitlab.gitops.local
        gitlab:
          name: gitlab.gitops.local
      rails:
        bootsnap:
          enabled: false
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    gitlab-runner:
      install: false
    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
      sidekiq:
        minReplicas: 1
        maxReplicas: 1
      gitlab-shell:
        minReplicas: 1
        maxReplicas: 1
    registry:
      hpa:
        minReplicas: 1
        maxReplicas: 1