---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 2m
  chart:
    spec:
      chart: rancher
      version: 2.5.1
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: gotk-system
      interval: 5m

  test:
    enable: false

  install:
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 1m
    cleanupOnFail: true

  dependsOn:
    - name: cert-manager
      namespace: cert-manager

  values:
    hostname: rancher.gitops.local
