---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 2m
  chart:
    spec:
      chart: loki-stack
      version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: gotk-system
      interval: 5m

  values:
    loki:
      enabled: true
      serviceMonitor:
        enabled: true

    promtail:
      enabled: true
      serviceMonitor:
        enabled: true

    grafana:
      enabled: false

    prometheus:
      enabled: false