varReference:
  - kind: HelmRelease
    path: spec/values/hostname
  - kind: VirtualService
    path: spec/hosts
  - kind: Gateway
    path: spec/servers/hosts
  - kind: Certificate
    path: spec/dnsNames