apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: global-configs
    namespace: gotk-system

vars:
  - name: hostname
    objref:
      kind: ConfigMap
      name: global-configs
      apiVersion: v1
    fieldref:
      fieldpath: data.hostname

configurations:
  - kconfig.yaml