---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: observability
spec:
  interval: 2m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 10.1.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: gotk-system
      interval: 5m

  test:
    enable: false

  install:
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 1m
    cleanupOnFail: true

  values:
    prometheusOperator:
      enabled: true
      manageCrds: true
      createCustomResource: true

    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 7.2.2
      additionalDataSources:
        - name: loki
          type: loki
          access: proxy
          url: http://loki.observability.svc.cluster.local:3100

    prometheus:
      enabled: true

    alertmanager:
      enabled: true