apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: default
  tag: 1.7.3-distroless
  meshConfig:
    accessLogFile: /dev/stdout
  addonComponents:

    kiali:
      enabled: true

    tracing:
      enabled: true

  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
      neverInjectSelector:
        - matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values: [fluentd-configcheck]

    kiali:
      dashboard:
        auth:
          strategy: anonymous
