---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: gotk-system
spec:
  interval: 2m

  chart:
    spec:
      chart: cert-manager
      version: v1.0.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: gotk-system
      interval: 5m

  test:
    enable: false

  install:
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 1m
    cleanupOnFail: true

  values:
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
        labels:
          release: monitoring
