---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
  namespace: observability
spec:
  interval: 2m
  chart:
    spec:
      chart: logging-operator
      version: 10.1.2
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: gotk-system
      interval: 5m

  test:
    enable: false

  install:
    remediation: # perform remediation when helm install fails
      retries: 5

  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true

  rollback:
    timeout: 1m
    cleanupOnFail: true

  dependsOn:
    - name: monitoring
      namespace: observability

  values:
    watchNamespace: observability
    createCustomResource: true
    monitoring:
      serviceMonitor:
        enabled: true