apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: istio-system
spec:
  secretName: wildcard-cert
  dnsNames:
    - "*.$(hostname)"
  issuerRef:
    name: ca
    kind: ClusterIssuer
