resources:
  # Admin tenant
  - ../base

  # Environment specific helm values created as kustomize config/secret generators
#  -

configMapGenerator:
  - name: global-configs
    namespace: gotk-system
    behavior: merge
    envs:
      - globals.env