resources:
  # Admin tenant
  - ../base

  # Environment specific entries
  - cert-manager/clusterissuer.yaml

  # Environment specific helm values created as kustomize config/secret generators
#  -

patchesStrategicMerge:
  - istio/patch-certificate.yaml

configMapGenerator:
  - name: global-configs
    namespace: gotk-system
    behavior: merge
    envs:
      - globals.env