resources:
  # Admin tenant
  - ../base

  # Environment specific entries
  - cert-manager/clusterissuer.yaml
  - istio/certificate.yaml

  # Environment specific helm values created as kustomize config/secret generators
#  -

components:
  - ../base/components/globals

configMapGenerator:
  - name: global-configs
    namespace: gotk-system
    behavior: merge
    envs:
      - globals.env
