---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
  namespace: observability
spec:
  interval: 2m
  chart:
    spec:
      chart: logging-operator
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
        namespace: gotk-system
      interval: 5m

  dependsOn:
    - name: monitoring
      namespace: observability

  values:
    watchNamespace: observability
    createCustomResource: false
    monitoring:
      serviceMonitor:
        enabled: true