resources:
  # Admin tenant
  - ../../cluster/admin

  # Steve tenant (in a real world scenario this would/should be applied separately)
  - ../../cluster/steve

  # Environment specific helm values created as kustomize config/secret generators
#  -

configMapGenerator:
  - name: global-configs
    namespace: gotk-system
    behavior: merge
    envs:
      - globals.env